import { emitToOrganization, emitToUser } from './notifications/socketService.js';
import { sendEmail } from './notifications/emailService.js';
import { env } from '../config/env.js';

const EMAIL_SUBJECTS = {
  'work_order:created': (payload) => `New work order ${payload.code || ''} - ${payload.title || 'Maintenance required'}`,
  'inspection:submitted': (payload) => `Inspection submitted - PQS ${payload.score ?? ''}`,
  'subscription:past_due': () => 'Action required: subscription payment overdue',
  'subscription:downgraded': () => 'Your subscription was downgraded to Free',
  'invoice:generated': (payload) => `Payment received - Invoice ${payload.invoiceNo || ''}`,
};

const buildEmailText = (event, payload) => {
  switch (event) {
    case 'work_order:created':
      return [
        `A new work order has been created${payload.autoGenerated ? ' automatically from an inspection' : ''}.`,
        `Code: ${payload.code}`,
        `Title: ${payload.title}`,
        `Priority: ${payload.priority}`,
        `Status: ${payload.status}`,
        '',
        'Sign in to TurfCare BD to view and assign it.',
      ].join('\n');
    case 'inspection:submitted':
      return [
        'An inspection has been submitted for review.',
        `Pitch quality score: ${payload.score} (${payload.tier})`,
        '',
        'Sign in to TurfCare BD to verify the inspection.',
      ].join('\n');
    case 'subscription:past_due':
      return [
        'Your subscription payment is overdue.',
        `Your plan will be downgraded to Free after the 7-day grace period unless payment is completed.`,
        '',
        'Sign in to TurfCare BD to renew your plan.',
      ].join('\n');
    case 'subscription:downgraded':
      return [
        'Your subscription has been downgraded to the Free plan.',
        'Upgrade any time from the Subscription settings to restore plan features.',
      ].join('\n');
    case 'invoice:generated':
      return [
        `Your payment of BDT ${payload.amount ?? ''} has been received.`,
        `Invoice No: ${payload.invoiceNo || ''}`,
        `Transaction ID: ${payload.tranId || ''}`,
        `Plan: ${payload.planId || ''}`,
        '',
        `View your invoice: ${env.frontendUrl}/payment/success?tran_id=${payload.tranId || ''}`,
        '',
        'Thank you for your payment!',
      ].join('\n');
    default:
      return `TurfCare BD notification: ${event}`;
  }
};

/**
 * In-app notification service — writes an audit log entry and emits a socket
 * event to the organization room (and optionally the affected user room).
 * Email notifications are sent to the organization's admins when the event
 * carries an email subject (SendGrid, console fallback when unconfigured).
 */
export const createNotificationService = ({ auditLogRepository, logger, userRepository }) => {
  const emailOrganizationAdmins = async (organizationId, event, payload) => {
    if (!EMAIL_SUBJECTS[event]) return;
    try {
      const admins = await userRepository.findMany({
        organizationId,
        role: 'org_admin',
        isActive: true,
      });
      const subject = EMAIL_SUBJECTS[event](payload);
      const text = buildEmailText(event, payload);
      await Promise.all(
        admins.map((admin) =>
          admin.email ? sendEmail({ to: admin.email, subject, text }) : Promise.resolve()
        )
      );
    } catch (err) {
      logger.warn(`Failed to email organization admins: ${err.message}`);
    }
  };

  const notifyOrganization = async (
    organizationId,
    event,
    payload = {},
    { actorId = null, ipAddress = null, action = null } = {}
  ) => {
    try {
      await auditLogRepository.create({
        organizationId,
        userId: actorId,
        action: action || event,
        resource: 'notification',
        resourceId: payload.workOrderId || payload.inspectionId || null,
        details: { event, payload },
        ipAddress,
      });
    } catch (err) {
      logger.warn(`Failed to persist notification audit log: ${err.message}`);
    }

    emitToOrganization(organizationId, event, {
      ...payload,
      emittedAt: new Date().toISOString(),
    });

    if (payload.assignedTo) {
      emitToUser(payload.assignedTo, event, {
        ...payload,
        emittedAt: new Date().toISOString(),
      });
    }

    emailOrganizationAdmins(organizationId, event, payload);

    return true;
  };

  const notifyUser = async (userId, event, payload = {}) => {
    emitToUser(userId, event, { ...payload, emittedAt: new Date().toISOString() });
    return true;
  };

  return { notifyOrganization, notifyUser };
};

export default createNotificationService;