import { AppError } from '../utils/ApiError.js';
import { sendEmail } from './notifications/emailService.js';

const FREQUENCIES = ['daily', 'weekly', 'monthly'];

const FREQUENCY_LABELS = {
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
};

const toLocalDateKey = (date) => {
  const d = new Date(date);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
};

const buildEmailHtml = ({ organizationName, frequency, dashboard, workOrderStatus, distribution }) => {
  const total = (dashboard?.totalInspections ?? 0) + (dashboard?.submittedInspections ?? 0);
  const avgScore = dashboard?.averageScore ?? dashboard?.avgScore ?? null;
  const rows = [
    ['Fields', dashboard?.totalFields ?? 0],
    ['Inspections', total],
    ['Average PQS', avgScore !== null ? Number(avgScore).toFixed(1) : '—'],
    ['Verified inspections', dashboard?.verifiedInspections ?? 0],
    ['Open work orders', dashboard?.openWorkOrders ?? 0],
  ];

  const statusRows = (workOrderStatus || [])
    .map((row) => `<tr><td>${row.status}</td><td>${row.count}</td></tr>`)
    .join('');

  const tierRows = (distribution?.tiers
    ? Object.entries(distribution.tiers).map(
        ([tier, count]) => `<tr><td>${tier}</td><td>${count}</td></tr>`
      )
    : []
  ).join('');

  return `
    <div style="font-family: Inter, Arial, sans-serif; max-width: 640px; margin: 0 auto; color: #0f172a;">
      <div style="background: #2563eb; padding: 24px 32px; border-radius: 12px 12px 0 0;">
        <h1 style="margin: 0; color: #fff; font-size: 20px;">TurfCare BD — ${FREQUENCY_LABELS[frequency]} Report</h1>
        <p style="margin: 6px 0 0; color: #dbeafe; font-size: 14px;">${organizationName}</p>
      </div>
      <div style="padding: 24px 32px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;">
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
          ${rows
            .map(
              ([label, value]) =>
                `<tr><td style="padding: 8px 0; color: #475569;">${label}</td><td style="padding: 8px 0; text-align: right; font-weight: 600;">${value}</td></tr>`
            )
            .join('')}
        </table>
        ${statusRows ? `<h3 style="margin: 24px 0 8px; font-size: 15px;">Work order status</h3><table style="width: 100%; border-collapse: collapse; font-size: 14px;">${statusRows}</table>` : ''}
        ${tierRows ? `<h3 style="margin: 24px 0 8px; font-size: 15px;">Score distribution</h3><table style="width: 100%; border-collapse: collapse; font-size: 14px;">${tierRows}</table>` : ''}
        <p style="margin: 24px 0 0; color: #94a3b8; font-size: 12px;">
          Generated by TurfCare BD on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}.
          Sign in to see detailed analytics: <a href="https://turfcare-bd.vercel.app/reports">View reports</a>
        </p>
      </div>
    </div>
  `;
};

const buildEmailText = ({ organizationName, frequency, dashboard, workOrderStatus }) => {
  const lines = [
    `TurfCare BD — ${FREQUENCY_LABELS[frequency]} report for ${organizationName}`,
    '',
    `Fields: ${dashboard?.totalFields ?? 0}`,
    `Inspections: ${dashboard?.totalInspections ?? 0}`,
    `Average PQS: ${dashboard?.averageScore ?? dashboard?.avgScore ?? '—'}`,
    `Open work orders: ${dashboard?.openWorkOrders ?? 0}`,
    '',
    ...(workOrderStatus || []).map((row) => `${row.status}: ${row.count}`),
    '',
    'Sign in to TurfCare BD for detailed analytics.',
  ];
  return lines.join('\n');
};

/**
 * Scheduled report service. Schedules are per-organization rows; the cron
 * worker calls runDue() periodically and emails each enabled schedule whose
 * window (day / week / month) has elapsed since lastRunAt.
 */
export const createScheduledReportService = ({
  scheduledReportRepository,
  organizationRepository,
  reportService,
  logger,
}) => {
  const isDue = (schedule, now = new Date()) => {
    if (!schedule.enabled) return false;
    const last = schedule.lastRunAt ? new Date(schedule.lastRunAt) : null;
    const todayKey = toLocalDateKey(now);

    switch (schedule.frequency) {
      case 'daily':
        return !last || toLocalDateKey(last) < todayKey;
      case 'weekly':
        return !last || now - last >= 7 * 24 * 60 * 60 * 1000;
      case 'monthly':
        if (!last) return true;
        return (
          last.getFullYear() < now.getFullYear() ||
          (last.getFullYear() === now.getFullYear() && last.getMonth() < now.getMonth())
        );
      default:
        return false;
    }
  };

  const buildReport = async (schedule) => {
    const [organization, dashboard, workOrderStatus, distribution] = await Promise.all([
      organizationRepository.findById(schedule.organizationId),
      reportService.getAnalytics(schedule.organizationId),
      reportService.getWorkOrderStatus(schedule.organizationId),
      reportService.getScoreDistribution(schedule.organizationId),
    ]);

    const base = {
      organizationName: organization?.name || 'My Organization',
      frequency: schedule.frequency,
      dashboard,
      workOrderStatus,
      distribution,
    };

    return {
      subject: `TurfCare BD ${FREQUENCY_LABELS[schedule.frequency]} report — ${base.organizationName}`,
      html: buildEmailHtml(base),
      text: buildEmailText(base),
    };
  };

  const runOne = async (schedule) => {
    const { subject, html, text } = await buildReport(schedule);
    const recipients = Array.isArray(schedule.recipients) ? schedule.recipients : [];
    const results = await Promise.all(
      recipients.map((to) => (to ? sendEmail({ to, subject, html, text }) : Promise.resolve({ ok: false })))
    );
    await scheduledReportRepository.update(schedule.id, { lastRunAt: new Date() });
    return { sent: results.filter((r) => r?.ok).length, total: recipients.length };
  };

  const runDue = async () => {
    const schedules = await scheduledReportRepository.listEnabled();
    const now = new Date();
    const results = [];
    for (const schedule of schedules) {
      try {
        if (isDue(schedule, now)) {
          const result = await runOne(schedule);
          results.push({ id: schedule.id, ...result });
        }
      } catch (err) {
        logger.error(`Scheduled report ${schedule.id} failed: ${err.message}`);
        results.push({ id: schedule.id, error: err.message });
      }
    }
    return results;
  };

  const list = async (organizationId) => {
    const schedules = await scheduledReportRepository.listByOrganization(organizationId);
    return schedules.map((s) => ({ ...s, recipients: s.recipients || [] }));
  };

  const validateInput = ({ frequency, recipients }) => {
    if (!FREQUENCIES.includes(frequency)) {
      throw new AppError(400, `Invalid frequency. Must be one of: ${FREQUENCIES.join(', ')}`, {
        code: 'INVALID_FREQUENCY',
      });
    }
    if (!Array.isArray(recipients) || recipients.length === 0 || recipients.some((r) => !r || typeof r !== 'string' || !r.includes('@'))) {
      throw new AppError(400, 'At least one valid recipient email is required', { code: 'INVALID_RECIPIENTS' });
    }
    return { frequency, recipients: recipients.map((r) => r.trim()) };
  };

  const upsert = async (organizationId, { id, frequency, recipients, enabled = true }) => {
    const input = validateInput({ frequency, recipients });
    return scheduledReportRepository.upsertForOrganization(organizationId, id || null, {
      ...input,
      enabled: Boolean(enabled),
    });
  };

  const remove = async (organizationId, id) => {
    const removed = await scheduledReportRepository.deleteForOrganization(id, organizationId);
    if (!removed) {
      throw new AppError(404, 'Scheduled report not found', { code: 'NOT_FOUND' });
    }
    return removed;
  };

  return { list, upsert, remove, runDue, isDue, FREQUENCIES };
};

export default createScheduledReportService;